### ISSUE TITLE
Use anchors in yaml files SE2

### ISSUE THREAD

**Issue by artemiy312** [fidals/stroyprombeton#370]
Anchors remove code duplication:
```yaml
run_tests: &run_tests
  image: python:latest
  commands:
    - python manage.py test

pipeline:
  pr:
    <<: *run_tests
    when:
      event: pull_request
      branch:
        excludes: master
  push:
    <<: *run_tests
    when:
      event: push
      branch: master
```
